In [1]:
def Bhargav():
    print('Hello')

In [2]:
Bhargav()

Hello


In [5]:
def greeting(name):
    print('Hello %s' %(name))

In [10]:
greeting('Bhargav')

Hello Bhargav


In [11]:
def addnum(num1,num2):
    return num1+num2

In [12]:
addnum(1034,444488899)

444489933

In [28]:
def checkPrime(num):
    '''
    Method to check prime or not
    '''
    for n in range(2,num):
        if num%n==0:
            print(num,'is not a prime Number' )
            break
    else:
            print(num,'is a prime Number')

In [32]:
checkPrime(522)

522 is not a prime Number


In [33]:
import math

def isPrime(num):
    if num % 2 ==0 and num > 2:
        return False
    for n in range(3, int(math.sqrt(num))+1, 2):
        if num%n == 0:
            return False
    return True

In [34]:
isPrime(256)

False

In [35]:
import numpy as np

In [36]:
list1=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [39]:
list1_array=np.array(list1)

In [40]:
list1_array.ndim

2

In [41]:
np.array(list1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
list1_array.shape

(4, 3)

In [44]:
list1_array.size

12

In [45]:
list1_array.dtype

dtype('int32')

In [46]:
list1_array.data

In [49]:
list2=np.arange(20).reshape(4,5)

In [50]:
list2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
list2.ndim

2

In [56]:
np.zeros([3,4], dtype=np.int64)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [58]:
np.empty((2,3), dtype=np.int16)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [60]:
np.arange(1,21,4)

array([ 1,  5,  9, 13, 17])

In [63]:
np.arange(0.2,4,0.3)

array([0.2, 0.5, 0.8, 1.1, 1.4, 1.7, 2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8])

In [64]:
from numpy import pi

In [65]:
np.linspace(1,2,9)

array([1.   , 1.125, 1.25 , 1.375, 1.5  , 1.625, 1.75 , 1.875, 2.   ])

In [67]:
x=np.linspace(1,2*pi,100)

In [68]:
np.sin(x)

array([ 8.41470985e-01,  8.69092889e-01,  8.94240311e-01,  9.16841651e-01,
        9.36832557e-01,  9.54156112e-01,  9.68762992e-01,  9.80611609e-01,
        9.89668226e-01,  9.95907059e-01,  9.99310343e-01,  9.99868390e-01,
        9.97579609e-01,  9.92450518e-01,  9.84495720e-01,  9.73737865e-01,
        9.60207581e-01,  9.43943393e-01,  9.24991607e-01,  9.03406184e-01,
        8.79248582e-01,  8.52587581e-01,  8.23499092e-01,  7.92065934e-01,
        7.58377605e-01,  7.22530022e-01,  6.84625251e-01,  6.44771213e-01,
        6.03081382e-01,  5.59674456e-01,  5.14674025e-01,  4.68208212e-01,
        4.20409317e-01,  3.71413431e-01,  3.21360056e-01,  2.70391705e-01,
        2.18653493e-01,  1.66292732e-01,  1.13458501e-01,  6.03012307e-02,
        6.97227097e-03, -4.63765403e-02, -9.95933081e-02, -1.52526514e-01,
       -2.05025446e-01, -2.56940629e-01, -3.08124250e-01, -3.58430580e-01,
       -4.07716385e-01, -4.55841339e-01, -5.02668422e-01, -5.48064306e-01,
       -5.91899740e-01, -

In [69]:
a=np.array([10,20,40,50,30])

In [72]:
b=np.arange(5)

In [73]:
c=a-b

In [74]:
c

array([10, 19, 38, 47, 26])

In [76]:
b**2.0

array([ 0.,  1.,  4.,  9., 16.])

In [78]:
np.sin(a)

array([-0.54402111,  0.91294525,  0.74511316, -0.26237485, -0.98803162])

In [83]:
A= np.array([[1,2],[4,5]])

In [84]:
B=np.array([[7,8],[10,11]])

In [85]:
A@B

array([[27, 30],
       [78, 87]])

In [87]:
a=np.random.random((2,3))

In [88]:
a

array([[0.93424933, 0.87903234, 0.8607512 ],
       [0.40372341, 0.95425759, 0.13633628]])

In [93]:
b=np.arange(12).reshape(3,4)

In [94]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
b.sum(axis=1)

array([ 6, 22, 38])

In [99]:
b.min(axis=1)

array([0, 4, 8])

In [100]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [105]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [106]:
c=np.arange(3)

In [107]:
c

array([0, 1, 2])

In [108]:
np.sqrt(c)

array([0.        , 1.        , 1.41421356])

In [109]:
np.exp(c)

array([1.        , 2.71828183, 7.3890561 ])

In [116]:
d=np.arange(10)**3

In [117]:
d

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [118]:
d[2:5]

array([ 8, 27, 64], dtype=int32)

In [121]:
d[:5]=1000

In [122]:
d

array([1000, 1000, 1000, 1000, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [124]:
d[:8:2]

array([1000, 1000, 1000,  216], dtype=int32)

In [126]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [127]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [130]:
c.shape

(2, 2, 3)

In [137]:
c[0,1,...]

array([4, 5, 6])

In [139]:
for i in c.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [142]:
a=np.floor(10*np.random.random((3,4)))

In [143]:
a

array([[0., 8., 9., 0.],
       [6., 3., 5., 2.],
       [8., 5., 4., 5.]])

In [144]:
a.ravel()

array([0., 8., 9., 0., 6., 3., 5., 2., 8., 5., 4., 5.])

In [146]:
a.reshape(6,2)

array([[0., 8.],
       [9., 0.],
       [6., 3.],
       [5., 2.],
       [8., 5.],
       [4., 5.]])

In [147]:
a

array([[0., 8., 9., 0.],
       [6., 3., 5., 2.],
       [8., 5., 4., 5.]])

In [148]:
a.T

array([[0., 6., 8.],
       [8., 3., 5.],
       [9., 5., 4.],
       [0., 2., 5.]])

In [150]:
a.T.shape

(4, 3)

In [151]:
a.shape

(3, 4)

In [152]:
a.ravel().shape

(12,)

In [153]:
a

array([[0., 8., 9., 0.],
       [6., 3., 5., 2.],
       [8., 5., 4., 5.]])

In [154]:
a.reshape(4,3)

array([[0., 8., 9.],
       [0., 6., 3.],
       [5., 2., 8.],
       [5., 4., 5.]])

In [158]:
a.resize(2,6)

In [159]:
a

array([[0., 8., 9., 0., 6., 3.],
       [5., 2., 8., 5., 4., 5.]])

In [160]:
a=np.floor(10*np.random.random((2,2)))

In [161]:
b=np.floor(10*np.random.random((2,2)))

In [162]:
np.vstack((a,b))

array([[6., 8.],
       [8., 4.],
       [2., 2.],
       [2., 5.]])

In [163]:
 np.hstack((a,b))

array([[6., 8., 2., 2.],
       [8., 4., 2., 5.]])

In [164]:
from numpy import newaxis

In [165]:
np.column_stack((a,b))

array([[6., 8., 2., 2.],
       [8., 4., 2., 5.]])

In [166]:
a

array([[6., 8.],
       [8., 4.]])

In [167]:
np.row_stack((a,b))

array([[6., 8.],
       [8., 4.],
       [2., 2.],
       [2., 5.]])

In [168]:
a

array([[6., 8.],
       [8., 4.]])

In [169]:
b

array([[2., 2.],
       [2., 5.]])

In [170]:
np.column_stack((a,b))

array([[6., 8., 2., 2.],
       [8., 4., 2., 5.]])

In [171]:
a=np.array([4,2,])

In [172]:
b=np.array([5,7,])

In [176]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4, 5],
       [2, 7]])

In [177]:
np.hstack((a[:,newaxis],b[:,newaxis]))

array([[4, 5],
       [2, 7]])

In [178]:
a[:,newaxis]

array([[4],
       [2]])

In [185]:
a=np.floor(10*np.random.random((2,12)))

In [186]:
a

array([[6., 6., 9., 4., 6., 3., 8., 7., 2., 3., 8., 6.],
       [1., 0., 5., 5., 6., 7., 9., 4., 6., 8., 9., 1.]])

In [187]:
np.hsplit(a,3)

[array([[6., 6., 9., 4.],
        [1., 0., 5., 5.]]), array([[6., 3., 8., 7.],
        [6., 7., 9., 4.]]), array([[2., 3., 8., 6.],
        [6., 8., 9., 1.]])]

In [188]:
a

array([[6., 6., 9., 4., 6., 3., 8., 7., 2., 3., 8., 6.],
       [1., 0., 5., 5., 6., 7., 9., 4., 6., 8., 9., 1.]])

In [189]:
c=a.view()

In [190]:
c is a

False

In [191]:
c.base is a

True

In [194]:
a=np.arange(12)**2

In [195]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [196]:
i=np.array([1,1,3,8,5])

In [197]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [265]:
a=np.arange(12).reshape(3,4)

In [266]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [267]:
i=np.array([[0,1],[1,2]])

In [268]:
a[i]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [248]:
j=np.array([[2,1],[3,3]])

In [269]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [227]:
a=np.arange(12)**2

In [228]:
j=np.array([[3,4],[9,7]])

In [231]:
j

array([[3, 4],
       [9, 7]])

In [230]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [232]:
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

In [270]:
a=np.array([1,2,3])

In [271]:
b=np.array([4,5,6])

In [272]:
c=np.array([7,8,9])

In [273]:
ax,bx,cx=np.ix_(a,b,c)

In [274]:
ax

array([[[1]],

       [[2]],

       [[3]]])

In [ ]:
ax.shape

In [276]:
bx

array([[[4],
        [5],
        [6]]])

In [277]:
cx

array([[[7, 8, 9]]])

In [278]:
bx.shape

(1, 3, 1)

In [279]:
cx.shape

(1, 1, 3)

In [280]:
result=ax+bx*cx

In [281]:
result

array([[[29, 33, 37],
        [36, 41, 46],
        [43, 49, 55]],

       [[30, 34, 38],
        [37, 42, 47],
        [44, 50, 56]],

       [[31, 35, 39],
        [38, 43, 48],
        [45, 51, 57]]])

In [284]:
result[0,1,2]

46

In [285]:
import numpy as np

In [289]:
print(np.__version__)

1.16.2


In [291]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [295]:
np.full((3,3), True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [296]:
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [298]:
arr[arr % 2 == 1 ]

array([1, 3, 5, 7, 9])

In [302]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [300]:
arr[ arr % 2 == 1 ] = -1

In [301]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [303]:
out=np.where(arr % 2 == 1, -1 ,arr)

In [304]:
print(out)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [305]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [311]:
out1=a.view()

In [312]:
out1

array([1, 2, 3])

In [315]:
np.arange(10).reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [316]:
a=np.arange(10).reshape(2,-1)

In [317]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [325]:
b=np.ones([2,5], dtype=np.int64).reshape(2,-1)

In [326]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [327]:
c=np.repeat(1,10).reshape(2,-1)

In [328]:
c

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [331]:
np.vstack((a,c))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [332]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]], dtype=int64)

In [333]:
a=np.array([1,2,3])

In [337]:
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [338]:
a=np.array([1,2,3,2,3,4,3,4,5,6])

In [339]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [342]:
np.intersect1d(a,b)

array([2, 4])

In [343]:
pwd

'C:\\Users\\Bhargav\\Desktop\\Complete-Python-3-Bootcamp-master\\03-Methods and Functions'